# # To get super user permissions
# sudo: required
# # To tell the Travis that we need Travis CI pre-installed
# services:
#   - docker
# # Any that should be done before tests executed.
# before_install:
#   - docker build -t scikit-surgerydocker .
# # This section contains the series of commands to test
# script:
#   - docker run scikit-surgerydocker